[package]
name = "slsk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
chrono = "0.4.31"
crossterm = "0.27.0"
md-5 = "0.10.6"
ratatui = "0.23.0"
smol = "1.3.0"
socket2 = "0.5.4"
tokio = {version = "1.33.0", features = ["net", "macros", "sync", "rt-multi-thread", "io-util"]}
tui-input = "0.8.0"
